### PR TITLE
iox-#2011 Silence some warnings when building with GCC 13.

### PR DESCRIPTION
**Pull request by clalancette**
GCC 13 (which is in Ubuntu 24.04) introduced a number of false positive warnings when using -Warray-bounds and -Wstring-op; see:

* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114758
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111118
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110807
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110498

In my testing, these only show up when building with optimizations, i.e. CMAKE_BUILD_TYPE=RelWithDebInfo.

This commit silences those warnings across the two functions that cause the problem, and make the build completely clean.

## Notes for Reviewer

This should fix the yellow builds in e.g. https://ci.ros2.org/view/packaging/job/packaging_linux/3451/
Note that this targets the `release_2.0` branch, since that is what ROS 2 is currently using.  If you'd like me to target another branch and then backport, I'm happy to do that instead.

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [N/A] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [N/A] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [N/A] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Consider a second reviewer for complex new features or larger refactorings
- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Relates to #2011

### CODE REVIEW

**Comment by elBoberido** [comment]
@clalancette we need to release v3.0 soonish. All of this is already fixed on the main branch.

The clang-tidy check might also bite us here. We might need to ignore it for this branch since the code was not yet fixed and it seems we also did not make it run with all files. Can you add `#include "iceoryx_hoofs/cxx/variant.hpp"` at the top of `variant.inl`? If clang-tidy continue to fail, we will just ignore it for this PR.

**Comment by elBoberido** [comment]
@clalancette oh, you already noticed to use #2011 as reference issue. Please adjust your commit message accordingly.

**Comment by elBoberido** [comment]
> > Can you add #include "iceoryx_hoofs/cxx/variant.hpp" at the top of variant.inl?
> 
> It looks like it is already there on the release_2.0 branch: https://github.com/eclipse-iceoryx/iceoryx/blob/release_2.0/iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl#L21
> 
> > @clalancette oh, you already noticed to use #2011 as reference issue. Please adjust your commit message accordingly.
> 
> My commit message already has "iox-#2011" as the first line of the commit message, but let me know if I need to change it to something else.



> > Can you add #include "iceoryx_hoofs/cxx/variant.hpp" at the top of variant.inl?
> 
> It looks like it is already there on the release_2.0 branch: https://github.com/eclipse-iceoryx/iceoryx/blob/release_2.0/iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl#L21

Oh, I confused the files. It seems the `variant_queue.inl` file is responsible for the CI failure.

> > @clalancette oh, you already noticed to use #2011 as reference issue. Please adjust your commit message accordingly.
> 
> My commit message already has "iox-#2011" as the first line of the commit message, but let me know if I need to change it to something else.

That's weird, it does not show up when I look at the commit. It says `Silence some warnings ...`

**Comment by clalancette** [comment]
> > 
> 
> That's weird, it does not show up when I look at the commit. It says `Silence some warnings ...`

You are right.  I fixed it locally, but I forgot to push it.  Pushed now.

**Comment by elBoberido** [comment]
> > > 
> > 
> > 
> > That's weird, it does not show up when I look at the commit. It says `Silence some warnings ...`
> 
> You are right. I fixed it locally, but I forgot to push it. Pushed now.

:smile: classic

Can you add `#include "iceoryx_hoofs/cxx/variant_queue.hpp"` to `iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_queue.inl`. It should fix the code linting job. I tested it locally.

What date would you prefer for a release?

**Comment by clalancette** [comment]
> Can you add `#include "iceoryx_hoofs/cxx/variant_queue.hpp"` to `iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_queue.inl`. It should fix the code linting job. I tested it locally.

Ah, great.  I've now updated and pushed that in 434ee45.  :crossed_fingers: 

> What date would you prefer for a release?

It is not a huge rush for us to get a release with this, but in the next month or so would be great.

**Comment by elBoberido** [comment]
> > What date would you prefer for a release?
> 
> It is not a huge rush for us to get a release with this, but in the next month or so would be great.

Let's see, maybe until then we find the time for the v3.0 release and also bring it to the ROS world.

**Pull request merged**
