### PR TITLE
iox-#1624 Fix typo

### LINKED ISSUE #1624: Fix typo
image

### PR DESCRIPTION
**Pull request by deneschen**
Signed-off-by: deneschen <deneschen@foxmail.com>

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1624

### CODE REVIEW

**Comment by elfenpiff** [comment]
@deneschen all what is left to do is that you sign the ECA (https://www.eclipse.org/legal/ECA.php) with `deneschen@foxmail.com` and we can merge it.

For this you have to create a account with the same mail in eclipse and press somewhere the agree or sign button.

**Review by elfenpiff — APPROVED** [review]

**Review by elBoberido — APPROVED** [review]

**Comment by elBoberido** [comment]
@deneschen thanks for your contribution. We just need to wait until the ECA is synced and then we can merge this.

**Comment by elfenpiff** [comment]
@deneschen the ECA is still not signed. Are you sure you signed it with "deneschen@foxmail.com".
It would be a pity when this wouldn't get merged because of this.

**Comment by deneschen** [comment]
@elfenpiff sorry I changed the github username, but not update the Eclipse user profile, now I updated.
I checked the status of Eclipse Contributor Agreement is ok, and the Account Settings of email address is deneschen@foxmail.com

**Comment by elBoberido** [comment]
@deneschen I think the ECA check is only triggered with a new commit. Could you maybe change the commit message to `Fix typo in chunk_header.hpp" and force push?

**Comment by deneschen** [comment]
@elBoberido @elfenpiff Thank you for your patience.

**Review by elBoberido — APPROVED** [review]

**Comment by elBoberido** [comment]
@deneschen thanks for your pation

**Review by elfenpiff — APPROVED** [review]

**Pull request merged**
