### PR TITLE
Iox #841 upgrade gtest gmock to v1.10

### LINKED ISSUE #841: Upgrade GTest/GMock to v1.10
## Brief feature description

GTest/GMock v1.10 introduced some new features which makes especially writing mocks a lot easier.

## Detailed information

With GMock v1.8 it is quite cumbersome to mock methods with the `noexcept` specifier since it is not possible to use the `MOCK_METHOD` directly and a delegation is needed. Since iceoryx uses this specifier all over the place its a PITA to write mocks with GMock v1.8

Assuming you want to mock the following class
```cpp
class Foo
{
  public:
    virtual bool bar(int, int) noexcept;
};
```

With GMock v1.8 the mock looks like this
```cpp
class FooMock : public Foo
{
  public:
    bool bar(int a, int b) noexcept override
    {
        return barMock(a, b);
    }

    MOCK_METHOD2(barMock, bool(int, int));
};
```

With GMock v1.10 it is much simpler
```cpp
class FooMock : public Foo
{
  public:
    MOCK_METHOD(bool, bar, (int, int), (noexcept override));
};
```

Furthermore, `override` can also directly be used, which helps to write more robust mocks.

Last but not least, we already use GTest/GMock v1.10 for Windows since v1.8  has issues on this platform.

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CHANGELOG.md

## Notes for Reviewer

This PR updates GTest/GMock to v1.10 and removes some workarounds caused by v1.8.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #841

### CODE REVIEW

**Review by mossmaurice — COMMENTED** [review]
LGTM! I know it's tiresome, but please adapt the year in all files with new code :upside_down_face:

**Comment by elBoberido** [comment]
> LGTM! I know it's tiresome, but please adapt the year in all files with new code upside_down_face

Sorry, but no. It was either code removal or mass search & replace. This is too trivial for a copyright update and we already handled it this way for other contributors.

**Review by FerdinandSpitzschnueffler — DISMISSED** [review]

**Comment by mossmaurice** [comment]
> Sorry, but no. It was either code removal or mass search & replace. This is too trivial for a copyright update and we already handled it this way for other contributors.

Understood and I think you're right to keep the copyright update process as simple as possible! As IANL and our previous workflow was:

* Remove code -> Old copyright header
* Code was changed or added -> Adapt copyright header

Hence, I would appreciate if we could discuss this topic in the next developer meetup.

cc @budrus

**Comment by elBoberido** [comment]
@mossmaurice INAL but the last time I talked with one about this the answer was `The change should be substantive before we claim Copyright protection` and I got a thumbs up for my question `so we can use common sense for this`. I hereby claim to not be insane (was not tested, so it's only a claim) and a mass search and replace does not count for copyright update ;)

cc @budrus

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Review by mossmaurice — APPROVED** [review]

**Pull request merged**
