### PR TITLE
Iox #653 fix roudi crash when replying to dead app

### LINKED ISSUE #653: Restarting an application can kill RouDi
## Required information

**Operating system:**
Ubuntu based

**Compiler version:**
all

**Observed result or behaviour:**
If an application is terminated and restarted before RouDi does the cleanup, RouDi crashes when doing the cleanup.

**Expected result or behaviour:**
RouDi should not crash

**Conditions where it occurred / Performed steps:**
Open two terminals and run `iox-roudi` in one of them.
Run `./iox-ex-subscriber&` in the second terminal, get the pid of the process e.g. with `ps aux | grep iox-ex-subscriber` and then run `kill -9 [PID]& ./iox-ex-subscriber`

RouDi terminates with
```
2021-03-29 12:19:51.746 [ Info  ]: No config file provided and also not found at '/etc/iceoryx/roudi_config.toml'. Falling back to built-in config.
Log level set to: [Warning]
Reserving 64550400 bytes in the shared memory [/iceoryx_mgmt]
[ Reserving shared memory successful ] 
Reserving 149134400 bytes in the shared memory [/apex]
[ Reserving shared memory successful ] 
RouDi is ready for clients
2021-03-29 12:20:20.851 [Warning]: Received REG from iox-ex-subscriber, but another application with this name is already registered
../iceoryx/iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:254 { iox::cxx::expected<iox::posix::IpcChannelError> iox::posix::UnixDomainSocket::timedSend(const string&, const iox::units::Duration&) const }  :::  [ 111 ]  Connection refused
../iceoryx/iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp:254 { iox::cxx::expected<iox::posix::IpcChannelError> iox::posix::UnixDomainSocket::timedSend(const string&, const iox::units::Duration&) const }  :::  [ 111 ]  Connection refused
No server for unix domain socket "/tmp/iox-ex-subscriber"
2021-03-29 12:20:20.852 [Warning]: Process cannot send message over communication channel
2021-03-29 12:20:20.852 [Warning]: ICEORYX error! POSH__ROUDI_PROCESS_SEND_VIA_IPC_CHANNEL_FAILED
iox-roudi: ../iceoryx/iceoryx_utils/source/error_handling/error_handling.cpp:61: static void iox::ErrorHandler::ReactOnErrorLevel(iox::ErrorLevel, const char*): Assertion `false' failed.
fish: “./iox-roudi” terminated by signal SIGABRT (Abbruch)
```

### PR DESCRIPTION
**Pull request by mossmaurice**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md

## Notes for Reviewer
* RouDi should never crash by wrong user input
* Combine monitored and un-monitored case and do not reply to dead app
* I've tested it manually as described in #653, as there is currently no framework available for such tests. I did intentionally not add any SWE.6 tests for it (@dkroenke FYI)
  *  **Please also test it manually**

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #653

### CODE REVIEW

**Review by marthtz — DISMISSED** [review]
Tested master and got the reported crash.
Tested the fix (w/ and w/o monitoring) and it worked.

**Review by elfenpiff — COMMENTED** [review]
Where are the tests?

**Review by elfenpiff — CHANGES_REQUESTED** [review]
Please add some kind of test!
Or how do you make sure that the crash is fixed?

**Review by elBoberido — DISMISSED** [review]

**Comment by mossmaurice** [comment]
> Please add some kind of test!
> Or how do you make sure that the crash is fixed?

Please have a look at the "Notes for Reviewer"

**Comment by elBoberido** [comment]
> Please add some kind of test!
> Or how do you make sure that the crash is fixed?

I think currently it can only be done manually by
- starting `iox-roudi`
- starting `./iox-ex-subscriber`
- executing `kill -9 [iox-ex-subscriber pid]& ./iox-ex-subscriber`

**Review by elBoberido — APPROVED** [review]

**Review by dkroenke — APPROVED** [review]

**Pull request merged**
