### PR TITLE
iox-#1393 Construct `DESTINATION_*` variables from `CMAKE_INSTALL_FULL_*DIR`

### LINKED ISSUE #1393: CMake config assumes relative `CMAKE_INSTALL_LIBDIR`
## Required information

**Operating system:**
Nix

**Compiler version:**
GCC 10.3.0

CMake allows the `CMAKE_INSTALL_*DIR` variables to be specified as absolute paths. This means they must not be concatenated with `CMAKE_INSTALL_PREFIX` in an attempt to form an absolute path. See here for more information: https://github.com/jtojnar/cmake-snips#assuming-cmake_install_dir-is-relative-path

`iceoryx_hoofs` [constructs `DESTINATION_CONFIGDIR` from `CMAKE_INSTALL_LIBDIR`](https://github.com/eclipse-iceoryx/iceoryx/blob/96de86cd21a0f9c090fda0685df32f9da34dad3b/iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake#L38) and then concatenates it with `CMAKE_INSTALL_PREFIX` [in `Config.cmake.in`](https://github.com/eclipse-iceoryx/iceoryx/blob/96de86cd21a0f9c090fda0685df32f9da34dad3b/iceoryx_hoofs/cmake/Config.cmake.in). The same pattern occurs in `iceoryx_posh`.

This can be fixed by constructing `DESTINATION_CONFIGDIR` from `CMAKE_INSTALL_FULL_LIBDIR` and then getting rid of the concatenation in `Config.cmake.in`.

### PR DESCRIPTION
**Pull request by lopsided98**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

Implements the solution described in #1393:

> This can be fixed by constructing DESTINATION_CONFIGDIR from CMAKE_INSTALL_FULL_LIBDIR and then getting rid of the concatenation in Config.cmake.in.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
    - [x] Each unit test case has a unique UUID
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1393

### CODE REVIEW

**Review by elfenpiff — COMMENTED** [review]
@lopsided98 Thanks for your contribution.

Something on the side, all cmake files have a copyright header where we acknowledge the contributors. If you like you can add there your name and the current year.

**Review by dkroenke — APPROVED** [review]
Approving for the case that the copyright headers aren't modified.

**Review by elfenpiff — APPROVED** [review]
@lopsided98 Please ping us if you would like to have this merged without adjusting the copyright header.

**Comment by lopsided98** [comment]
@elfenpiff I'm fine with not changing the header.

**Pull request merged**
