### PR TITLE
iox-#2272 Make iceoryx resource prefix a compile time option

### LINKED ISSUE #2272: Make iceoryx resource prefix a compile time option
## Brief feature description

In #2258 we got reminded that it might be helpful to create complete islands for an iceoryx deployment. Since all the resources now have a prefix, the next logical step would be to make it a compile time option.

With this, one could run a separate iceoryx application network without interfering e.g. with ROS2 applications using Cyclone DDS with iceoryx as local transport.

### PR DESCRIPTION
**Pull request by elBoberido**
## Notes for Reviewer

This PR makes the resource prefix a compile time option

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Consider a second reviewer for complex new features or larger refactorings
- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #2272

### CODE REVIEW

**Comment by elBoberido** [comment]
@ximion if you compile with `-DIOX_DEFAULT_RESOURCE_PREFIX=foo` you can create your own island with iceoryx applications without interference from ROS2 applications running with Cyclone DDS and iceoryx.

**Comment by ximion** [comment]
> @ximion if you compile with `-DIOX_DEFAULT_RESOURCE_PREFIX=foo` you can create your own island with iceoryx applications without interference from ROS2 applications running with Cyclone DDS and iceoryx.

Oh wow, this is super nice, thank you! I'll test it :-)
One drawback is that this will make it hard for people to compile my app and ROS2 using Linux-distribution-provided iceoryx packages - I would basically have to vendor IOX, which is slightly inconvenient. But I guess a lot of values are compile-time constants in IOX for performance and to simplify memory management, and this will make it possible for bespoke deployments to run both tools at the same time, which is *incredibly* nice and removes a big potential obstacle for when we switched to iceoryx :-)

Thank you!

**Review by elfenpiff — APPROVED** [review]

**Comment by elBoberido** [comment]
> > @ximion if you compile with `-DIOX_DEFAULT_RESOURCE_PREFIX=foo` you can create your own island with iceoryx applications without interference from ROS2 applications running with Cyclone DDS and iceoryx.
> 
> Oh wow, this is super nice, thank you! I'll test it :-) One drawback is that this will make it hard for people to compile my app and ROS2 using Linux-distribution-provided iceoryx packages - I would basically have to vendor IOX, which is slightly inconvenient. But I guess a lot of values are compile-time constants in IOX for performance and to simplify memory management, and this will make it possible for bespoke deployments to run both tools at the same time, which is _incredibly_ nice and removes a big potential obstacle for when we switched to iceoryx :-)
> 
> Thank you!

@ximion it shouldn't be too hard to make this a run time option but I'm lacking time at the moment. Patches are welcome :)

**Comment by ximion** [comment]
> @ximion it shouldn't be too hard to make this a run time option but I'm lacking time at the moment. Patches are welcome :)

That looks doable! Once the journal review I'm working on is done I'll look into this :-)

**Comment by elBoberido** [comment]
Great. You can ping us in the gitter chat or open a new discussion in the repo. We could give you some hints to get you up to speed :)

**Pull request merged**
