### PR TITLE
iox-#454 improve coverage of class roudi memory provider, memory block and memory manager

### LINKED ISSUE #454: Enhancing Tests in Roudi
## Brief feature description
Introduce Module tests for RouDi component.

## Detailed information
Increase the code coverage.

Classes in RouDi components which needs test cases to be added.
In file roudi.cpp, class 
- [ ] RouDi.

In file roudi_process.cpp class 
- [x] RouDiProcess
- [x] PortManager
- [ ] ProcessManager
- [ ] RoudiMemoryManager

In file roudi_lock.cpp class 
- [ ] RouDiLock

### PR DESCRIPTION
**Pull request by nihalchari**
## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Notes for Reviewer
code contributed by @JimmyBch

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [x] All checkboxes in the PR checklist are checked or crossed out
1. [ ] Merge

## References

- partly closes #454

### CODE REVIEW

**Comment by nihalchari** [comment]
closed https://github.com/eclipse-iceoryx/iceoryx/pull/478 and created new

**Comment by JimmyBch** [comment]
@elBoberido @dkroenke Do you mind to review this PR and give your approval whether everything is ok ? :)

**Comment by dkroenke** [comment]
@nihalchari or @JimmyBch please fill in the Pre-Review Checklist of the PR description

**Review by dkroenke — DISMISSED** [review]

**Review by elBoberido — DISMISSED** [review]

**Comment by FerdinandSpitzschnueffler** [comment]
Can you please update the copyright headers in the changed files so that they include the years of the creation and of the last modification, i.e. ``2019, 2021``?

**Comment by elBoberido** [comment]
@FerdinandSpitzschnueffler we didn't do it for files which were created in 2019 and adapted in 2020, so I'm not sure if we have to. I would prefer not to do it if not necessary.

**Review by dkroenke — DISMISSED** [review]

**Review by elBoberido — APPROVED** [review]

**Review by dkroenke — APPROVED** [review]

**Pull request merged**
