### PR TITLE
Apply patch after adding external project

### PR DESCRIPTION
**Pull request by Blast545**
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

This PR attempts to fix some warnings in the ROS2 buildframs, it will need to be backported to release1.0 as well.

References: https://build.ros2.org/view/Rci/job/Rci__nightly-release_ubuntu_jammy_amd64/39/cmake/new/folder.-1345874543/
https://build.ros2.org/view/Gci/job/Gci__nightly-release_ubuntu_focal_amd64/112/cmake/

What happens with the current code in the buildfarm is that `colcon build` is called twice and the build process for the external projects occurs twice. As the build steps for the external project are not checked against previous builds, the patch command is used twice, causing a warning the second time it happens because it's not valid there.

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [ ] Tests follow the [best practice for testing][testing]
1. [ ] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [ ] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [ ] Commits messages are according to this [guideline][commit-guidelines]
    - [ ] Commit messages have the issue ID (`iox-#123 commit text`)
    - [ ] Commit messages are signed (`git commit -s`)
    - [ ] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [ ] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [ ] Relevant issues are linked
1. [ ] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. [ ] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
    - [ ] Each unit test case has a unique UUID
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes **TBD**

### CODE REVIEW

**Comment by Blast545** [comment]
FYI: @clalancette

**Comment by elfenpiff** [comment]
@Blast545 Thanks for your contribution. Since we are a project in a safety critical domain we have to ensure traceability all the time. To ensure this I created an issue, see #1323 . Could you please adjust your commit message so that it contains the `iox-#1323 ` prefix.

This can be done with:
```
git rebase -i HEAD~1
```
* replace `pick` with `edit` and save the file
```
git commit --amend
```
* add the prefix and finalize the rebase with `git rebase --continue`.
* Push it with `git push -f`.

Furthermore, since we are an eclipse project you have to sign the eclipse ECA for every contribution, see https://www.eclipse.org/legal/ecafaq.php#:~:text=How%20do%20I%20sign%20a,%22;%20and%20Complete%20the%20form.

**Comment by dkroenke** [comment]
Hi @Blast545,
thank you for the heads up to the CMake warning and the Pull-Request.
We did an investigation on this we came to the conclusion that this change would break the recursive build in iceoryx when building outside of colcon.
This would happen when calling the following command twice:
```
./tools/iceoryx_build_test.sh build-all
```

But still the issue needs of course a solution where we are working on. We will create a separate Pull-Request that removes the git patch for cpptoml and apply the missing header directly. We will ping you when the PR is opened by us.

FYI @elBoberido @clalancette

**Comment by Blast545** [comment]
@elfenpiff @dkroenke @elBoberido Thanks a lot for looking so promptly into this! :raised_hands:

**Pull request closed without merging**
