### PR TITLE
iox-#2364 Fix Bzlmod module name typo

### LINKED ISSUE #2364: Fix Bazel Typo
## Required information

Currently if you want to depend on Iceoryx as a Bzlmod bazel_dep you have to do something like
```Starlark
bazel_dep(name = "org_eclipse_iceroyx", repo_name = "iceoryx")
git_override(
    module_name = "org_eclipse_iceroyx",
    commit = "00c5349eabfb1bce5db46efefb39fd9471679be1",
    patches = ["//third_party/iceoryx:iceoryx.patch"],
    remote = "https://github.com/eclipse-iceoryx/iceoryx",
)
```

It would be nice to fix that typo.

I'll send some follow up PRs to contribute patches that make depending on the module via Bzlmod actually work.

### PR DESCRIPTION
**Pull request by lalten**
## Notes for Reviewer

Currently if you want to depend on Iceoryx as a Bzlmod bazel_dep you have to do something like
```Starlark
bazel_dep(name = "org_eclipse_iceroyx", repo_name = "iceoryx")
git_override(
    module_name = "org_eclipse_iceroyx",
    commit = "00c5349eabfb1bce5db46efefb39fd9471679be1",
    patches = ["//third_party/iceoryx:iceoryx.patch"],
    remote = "https://github.com/eclipse-iceoryx/iceoryx",
)
```

It would be nice to fix that typo.

I'll send some follow up PRs to contribute patches that make depending on the module via Bzlmod actually work.

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/main/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Consider a second reviewer for complex new features or larger refactorings
- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #2364

### CODE REVIEW

**Comment by lalten** [comment]
@elfenpiff please have another look.

**Comment by elfenpiff** [comment]
@lalten Looks good. I created this issue #2364 for you. Could you please adjust your commit message so that the prefix is `iox-#2364` - then we can merge this PR.

**Review by elfenpiff — APPROVED** [review]

**Comment by lalten** [comment]
@elfenpiff anything left to do on my side for this PR?

**Comment by elBoberido** [comment]
@lalten can you please rebase? We deactivated the Cirrus CI on main since we ran out of credits for the open source project.

**Comment by elBoberido** [comment]
@lalten thanks for your contribution and sorry letting you wait so long with the merge :)

**Pull request merged**
