### PR TITLE
iox-#1391 Move dust header from legacy path to module path part 3

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

This PR moves the posix wrapper in iceoryx dust to the new module location.

Additionally `IOX_EXPECTS_WITH_MSG` and `IOX_DEPRECATED_SINCE` is used where appropriate.

Finally it also fixes a race condition in the `PortUser_IntegrationTest` which was uncovered on the aarch64 build.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Relates to #1391

### CODE REVIEW

**Comment by elBoberido** [comment]
@mossmaurice @elfenpiff after moving the first posix wrapper to the new module structure and making the include structure flat I'm a bit hesitant with the flat namespace and includes for posix and concurrent.

I think it might make sense to have a `iox/posix/foo.hpp` include and a respective `iox::posix::FOO` access. There are quite some helper types which might class when we don't do this.

There is also half of a precedence for this, we use `iox::units::Duration` instead of just `iox::Duration`. Although the include is `iox/duration.hpp`. This is also confusing and we should move the include to `iox/units/duration.hpp`.

In general I thin we should have the flat structure for general constructs like `vector` or when the class is not part of a bigger logical group of its own. `posix` and `concurrent` are bigger logical groups which have some implications when used and would warrant an additional layer in the namespace and include path.

Do you agree to keep those namespaces and have the include path mirror the namespace (with the exception of the detail folder)?

**Comment by elBoberido** [comment]
@dkroenke @MatthiasKillat @FerdinandSpitzschnueffler  ^^^ although you were not part of the original discussion, your input is also welcome

**Comment by FerdinandSpitzschnueffler** [comment]
> @mossmaurice @elfenpiff after moving the first posix wrapper to the new module structure and making the include structure flat I'm a bit hesitant with the flat namespace and includes for posix and concurrent.
> 
> I think it might make sense to have a `iox/posix/foo.hpp` include and a respective `iox::posix::FOO` access. There are quite some helper types which might class when we don't do this.
> 
> There is also half of a precedence for this, we use `iox::units::Duration` instead of just `iox::Duration`. Although the include is `iox/duration.hpp`. This is also confusing and we should move the include to `iox/units/duration.hpp`.
> 
> In general I thin we should have the flat structure for general constructs like `vector` or when the class is not part of a bigger logical group of its own. `posix` and `concurrent` are bigger logical groups which have some implications when used and would warrant an additional layer in the namespace and include path.
> 
> Do you agree to keep those namespaces and have the include path mirror the namespace (with the exception of the detail folder)?

I agree that it makes sense to keep the `posix` and the `concurrent` namespace. Since you mentioned `Duration`: I don't see why we should keep the `units` namespace. Can't we just remove it? If something speaks against it, can we at least make the include path (`time`) and the namespace (`units`) consistent?

**Comment by elBoberido** [comment]
@FerdinandSpitzschnueffler @mossmaurice @dkroenke @MatthiasKillat @elfenpiff @budrus feel free to add yourself as reviewer

I kept `posix` in the include path and as namespace for now. We also need to think about clear guidelines for this or remove it as part of #1593 because it is not as clear as I hoped. For example, there is a `deadline_timer` directly in `iox`. Initially it used `chrono` to get the current time but eventually was ported to `clock_gettime` which would make it a candidate to be moved to `posix` but then the include paths and namespaces would change. I'll put this on the agenda for the next meeting. We have to weight in all the pros and cons.

I'll continue to keep `posix` as namespace and in the include paths while moving the files to the new module structure for now. It can be changed later on with #1593 if we decide so.

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Review by elfenpiff — APPROVED** [review]

**Pull request merged**
