### PR TITLE
iox-#1919-fix-max-group-name-length

### LINKED ISSUE #1919: MAX_GROUP_NAME_LENGTH should be at least equal to MAX_USER_NAME_LENGTH
## Required information

**Operating system:**
Any supported

**Compiler version:**
Any supported

**Eclipse iceoryx version:**
`master`

**Observed result or behaviour:**
Since by default `adduser`/`useradd` add the user to a group with the same name as the new user's login name (see [the docs](https://linux.die.net/man/8/adduser)), any user with a login name longer than 16 characters cannot run RouDi out of the box without changing their group settings (which they might not want to/be allowed to do). Since longer login names are allowed (up to `32` chars), longer group names should also be allowed (also up to `32` chars).

Edit: `groupadd` [documentation](https://linux.die.net/man/8/groupadd) also mentions `32` chars as the limit.

**Expected result or behaviour:**
Everyone can happily run RouDi out of the box. To this goal, `MAX_GROUP_NAME_LENGTH` should be set to `32` here: https://github.com/eclipse-iceoryx/iceoryx/blob/b10cc415c9ccf0d00d84681e2560d5636e61fb30/iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_access_rights.hpp

**Conditions where it occurred / Performed steps:**
- Make a new user with login name `0myname.mysurname` (17 chars), without specifying any group, so that it will be added to the default group `0myname.mysurname`
- Run RouDi with default configuration: `./iox-roudi`
- You will get this error message: `[Error]: Error: Could not find group "0myname.mysurnam"` (notice that the last character has been truncated).

### PR DESCRIPTION
**Pull request by atirehgram**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #1919

### CODE REVIEW

**Comment by elfenpiff** [comment]
@atirehgram did you sign the eclipse eca yet? https://www.eclipse.org/legal/ECA.php

This is required by every committer. For this you require an eclipse account which uses the same email address you used for the commits here and has signed the eclipse committer agreement.

**Review by elfenpiff — COMMENTED** [review]
Looks good, as soon as the ECA is signed it can be merged.

If you like you can add your name in the copyright header of every file you have modified:
```
// Copyright (c) 2023 by ???. All rights reserved.
```
But this is optional and up to you.

**Comment by atirehgram** [comment]
> @atirehgram did you sign the eclipse eca yet? https://www.eclipse.org/legal/ECA.php
> 
> This is required by every committer. For this you require an eclipse account which uses the same email address you used for the commits here and has signed the eclipse committer agreement.

Sorry, I forgot with which email I had signed it. It should be fine now, could you please retrigger the check?

**Comment by elfenpiff** [comment]
@atirehgram eclipse does not want to verify it. It states: `margherita.protti@****.com` failed. Could you may please check again if you signed with the same email address the ECA you committed with.

And I will retry it in the afternoon again - maybe eclipse requires just some more time. Most of the times eclipse is just a little bit weird and slow.

**Comment by atirehgram** [comment]
I double checked the mail in the ECA and I also retriggered the check manually twice, but it keeps failing.

**Comment by elfenpiff** [comment]
@atirehgram we have a hard internal deadline for a feature until Thursday. I would retrigger the check again and on Friday I would start digging here deeper.

But when we are lucky the problem is just vanished until then.

**Comment by elfenpiff** [comment]
@atirehgram I think eclipse somehow screws up here and after trying the 1000th captcha challenge of trying to find a hamster in its natural environment I would propose the following.

* Could you please split up your commits into two with the correct author and force push it. Maybe the eclipse thingy has your email cached somewhere and therefore it does not validate it.
* If this does not work I would create an eclipse bug ticket.

One question, did you change the commits author or had multiple authors for one commit? This could maybe explain the eclipse bug - but it is still an eclipse bug.

**Comment by elfenpiff** [comment]
@atirehgram I have found the problem. When you take a look at your commit with `git log --format=fuller` you see:

```
commit b2b0047e7516e7e0e3e38f5493111255f20f724a (HEAD -> iox-1919-fix-max-group-name-length, foo/iox-1919-fix-max-group-name-length)
Author:     Margherita Protti <margherita.protti@agile-robots.com>
AuthorDate: Mon Feb 27 14:17:33 2023 +0100
Commit:     Margherita Protti <margherita.protti@gmail.com>
CommitDate: Tue Feb 28 08:32:27 2023 +0100
```

So it seems you have somehow an author but a different committer (I didn't know that this was possible). The e-mail in the `author` section has to sign the ECA. And usually the author and committer are the same I suspect. So could you please use the same email for commit and author and then we can get this PR in.

I think you may have to rebase to master again since it shows now a merge conflict with our release notes.

But when we handled this PR sucessfully the next PRs from your side will be much smoother. Eclipse with its ECA is not so welcoming to newcomers :/ ...

**Review by elfenpiff — APPROVED** [review]

**Pull request merged**
