### PR TITLE
iox-#1977 ServiceDescription Interfaces and INTERFACE_NAMES do not match

### PR DESCRIPTION
**Pull request by wjswjq**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes **https://github.com/eclipse-iceoryx/iceoryx/issues/1977**

### CODE REVIEW

**Review by mossmaurice — APPROVED** [review]
LGTM, thanks!


@wjswjq I just noticed that the Eclipse ECA check is failing. Have you created an Eclipse account with the same email address and signed the [ECA](https://www.eclipse.org/projects/handbook/#contributing-eca)?

**Comment by wjswjq** [comment]
> LGTM, thanks!
> 
> @wjswjq I just noticed that the Eclipse ECA check is failing. Have you created an Eclipse account with the same email address and signed the [ECA](https://www.eclipse.org/projects/handbook/#contributing-eca)?

Not the same email address. My email is `wjswjq@qq.com` in Eclipse account, while `wangjinqian@lixiang.com` in commit message. Do they need to be consistent?

**Comment by mossmaurice** [comment]
> Not the same email address. My email is wjswjq@qq.com in Eclipse account, while wangjinqian@lixiang.com in commit message. Do they need to be consistent?

@wjswjq Yes, I think they need to be the same.

**Comment by wjswjq** [comment]
> @wjswjq Yes, I think they need to be the same.

@mossmaurice I've updated my ECA. Now they are both `wangjinqian@lixiang.com`

**Comment by mossmaurice** [comment]
@wjswjq 

> @mossmaurice I've updated my ECA. Now they are both `wangjinqian@lixiang.com`

That worked, thanks! :tada: 

Regarding the item in the checklist

>  Copyright owner are updated in the changed files

if you want you can add your copyright in the copyright header. This is optional, though.

**Comment by wjswjq** [comment]
> if you want you can add your copyright in the copyright header. This is optional, though.

@mossmaurice Not needed. Thanks.

**Pull request merged**
