### PR TITLE
iox-#1391 Move 'AccessMode' and 'OpenMode' to 'filesystem.hpp'

### PR DESCRIPTION
**Pull request by elBoberido**
## Pre-Review Checklist for the PR Author

1. [x] Add a second reviewer for complex new features or larger refactorings
1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] ~~Changelog updated [in the unreleased section][changelog] including API breaking changes~~
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

This PR moves the `AccessMode` and `OpenMode` enums and the corresponding free functions to `filesystem.hpp` an removes the `types.hpp`. Originally (i.e. v2.0) these types were defined in `shared_memory_object/shared_memory.hpp`. Therefore I also put the deprecation marker into that file.

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Relates to #1391

### CODE REVIEW

**Comment by elBoberido** [comment]
@mossmaurice @FerdinandSpitzschnueffler @elfenpiff this is the first time I move a header within hoofs in the context of #1391. I did not find anything in the release notes for this issue. Since you already moved some header, was the idea to add this to the release notes once the task is finished?

**Comment by FerdinandSpitzschnueffler** [comment]
> @mossmaurice @FerdinandSpitzschnueffler @elfenpiff this is the first time I move a header within hoofs in the context of #1391. I did not find anything in the release notes for this issue. Since you already moved some header, was the idea to add this to the release notes once the task is finished?

@elBoberido If I remember correctly, we followed this procedure:
- if only the namespace and path were changed, we just updated any occurrences in the release notes
- if a class was renamed or any other "bigger" refactoring was done, like the `helplets` split, we added an extra entry to the release notes
I think the plan was to add a "several namespaces/include paths have changed"-like entry after the task is finished/before the next release. Can you confirm, @mossmaurice?

**Comment by elBoberido** [comment]
@FerdinandSpitzschnueffler thanks. Makes sense.

**Comment by elBoberido** [comment]
@FerdinandSpitzschnueffler @mossmaurice @dkroenke @MatthiasKillat @budrus feel free to add yourself as reviewer

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Pull request merged**
