### PR TITLE
iox-#2072 Include mqueue.h needs sys/stat.h for mode_t (fixes musl compile)

### LINKED ISSUE #2072: Compile with musl libc fails:  error: 'mode_t' has not been declared
## Required information

**Operating system:**
openSUSE Tumbleweed/Buildroot

**Compiler version:**
GCC 12.3.0

**Eclipse iceoryx version:**
`v2.0.3`  and git `master` branch

**Observed result or behaviour:**
Compile fails (using buildroot with musl libc selected) with the following error message:

      In file included from .../build/iceoryx-custom/iceoryx_platform/linux/source/mqueue.cpp:17:
      .../build/iceoryx-custom/iceoryx_platform/linux/include/iceoryx_platform/mqueue.hpp:23:49: error: ‘mode_t’ has not been declared
         23 | mqd_t iox_mq_open4(const char* name, int oflag, mode_t mode, struct mq_attr* attr);
            |                                                 ^~~~~~
      .../build/iceoryx-custom/iceoryx_platform/linux/source/mqueue.cpp:26:49: error: ‘mode_t’ has not been declared
         26 | mqd_t iox_mq_open4(const char* name, int oflag, mode_t mode, struct mq_attr* attr)
            |                                                 ^~~~~~

**Expected result or behaviour:**
Compile without failure...

**Conditions where it occurred / Performed steps:**
Crosscompile using Buildroot and musl libc selected in the configuration

### PR DESCRIPTION
**Pull request by pseiderer**
As stated in the mq_open man page ([1]) the mqueue.h include needs additional sys/stat.h include for mode_t definition.

Fixes musl compile:

  In file included from .../build/iceoryx-custom/iceoryx_platform/linux/source/mqueue.cpp:17:
  .../build/iceoryx-custom/iceoryx_platform/linux/include/iceoryx_platform/mqueue.hpp:23:49: error: ‘mode_t’ has not been declared
     23 | mqd_t iox_mq_open4(const char* name, int oflag, mode_t mode, struct mq_attr* attr);
        |                                                 ^~~~~~
  .../build/iceoryx-custom/iceoryx_platform/linux/source/mqueue.cpp:26:49: error: ‘mode_t’ has not been declared
     26 | mqd_t iox_mq_open4(const char* name, int oflag, mode_t mode, struct mq_attr* attr)
        |                                                 ^~~~~~

[1] https://man7.org/linux/man-pages/man3/mq_open.3.html

## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #2072

### CODE REVIEW

**Review by elBoberido — APPROVED** [review]
If you did not yet sign the ECA please do it, else the CI prevents to merge the PR. If you already signed it, it might take a day or two to sync.

Thanks for your contribution

**Comment by elBoberido** [comment]
Oh, it seems you need to run clang-format or manually sort the includes in alphabetical order

**Comment by elBoberido** [comment]
@pseiderer Okay, now the CI is fine. Would you please also add the fixed issue to the changelog? The link is in the PR template.

Once that is done we just have to wait for the ECA check to pass

**Review by elBoberido — APPROVED** [review]
Looks good now. Thanks for your contribution

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Pull request merged**
