### PR TITLE
iox-#533 Add Installation guide after building.

### LINKED ISSUE #533: Add how to install after build to guide.
I found there is lack of information on how to install after building.
so, this is just a small patch and the first PR for me to learn rules of how to contribute this project.
https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by BH1SCW**
Signed-off-by: Fanjun Kong <bh1scw@gmail.com>

## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [x] All checkboxes in the PR checklist are checked or crossed out
1. [x] Merge

## References

- Closes **TBD**

Fixes #533"

### CODE REVIEW

**Comment by mossmaurice** [comment]
Thanks for your contribution! :-) 
Could you go through the list "Pre-Review Checklist for the PR Author" and tick the checkboxes? Please also add a link e.g. "Fixes #533" at the very bottom of the pull request description.

**Comment by BH1SCW** [comment]
> Thanks for your contribution! :-)
> Could you go through the list "Pre-Review Checklist for the PR Author" and tick the checkboxes? Please also add a link e.g. "Fixes #533" at the very bottom of the pull request description.

Thanks for your  advice:) I have finished all above, could you help to check again?
Best wishes.

**Review by dkroenke — APPROVED** [review]
Only one formal point:
You can use the bulletpoint `Closes TBD` in the PR Template for linking to the corresponding issue. This would come here then with `Closes #533`.
Using the keyword `Fixes` is of course also valid.

**Review by mossmaurice — APPROVED** [review]

**Comment by BH1SCW** [comment]
Hi dkroenke, 
I will keep your advice in mind for the next time.
Thanks a bunch!

**Pull request merged**
