### PR TITLE
Clarify documentation of optionals

### PR DESCRIPTION
**Pull request by tobiasblass**
## Pre-Review Checklist for the PR Author

1. [ ] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [ ] Tests follow the [best practice for testing][testing]
1. [ ] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [ ] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [ ] Commits messages are according to this [guideline][commit-guidelines]
    - [ ] Commit messages have the issue ID (`iox-#123 commit text`)
    - [ ] Commit messages are signed (`git commit -s`)
    - [ ] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [ ] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [ ] Relevant issues are linked
1. [ ] Add sensible notes for the reviewer
1. [ ] All checks have passed (except `task-list-completed`)
1. [ ] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/advanced/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
    - [ ] Each unit test case has a unique UUID
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes **TBD**

### CODE REVIEW

**Comment by tobiasblass** [comment]
@mossmaurice It seems like the PR checklist assumes that a contributor can open a branch in the iceoryx repository, has signed the legal agreements, and opens an issue in before-hand.

This seems like a lot of overhead for these minor documentation improvements. Maybe it's easier if you just re-commit the commits under your name.

**Comment by elfenpiff** [comment]
@tobiasblass 

> It seems like the PR checklist assumes that a contributor can open a branch in the iceoryx repository,

This is not the case, why do you have this impression? At the moment the workflow is just to create a branch on the https://github.com/apexai/iceoryx fork (for Apex.AI employees) otherwise on your private fork.

> has signed the legal agreements, 

This is something you only have to do once. See: https://www.eclipse.org/legal/ECA.php Just create an account with the same E-Mail you use in your commits and sign the ECA.

> and opens an issue in before-hand.

This is required since we have to ensure traceability. Therefore the workflow is like this:
1. Create issue (For small things like this PR the issue can consists of one or two sentences)
2. Create a branch with the prefix `iox-#???` where `???` is the issue number
3. Use in every commit the prefiox `iox-#???`
4. The PR name also requires the `iox-#???` prefix and is then linked with the issue.

> This seems like a lot of overhead for these minor documentation improvements.

The overhead is actually quite minimal. Signing the ECA once costs you 5 minutes and the rest goes with the flow. So could you please sign the ECA, create the issue, rename your branch and perform a rebase to adjust your commit messages, like:
```
git rebase -i HEAD~2
# change pick to edit for both commits
git commit --amend
# add the iox-#??? and continue to the next commit with git rebase --continue
git push -f # force push since you changed the history
```

Starting in a new open source project comes always with a little bit of overhead but the next issue will cost you only one additional minute since now you know the process :D ...

> Maybe it's easier if you just re-commit the commits under your name.

No I would not do this. You made a contribution and we are all thankful for that and therefore your name should be mentioned, even when it is just a minor change. Also we want to be clear and transparent for everyone and those hacks may provide the wrong impression.


@tobiasblass From your point of view, do you have any suggestions for us how to make it easier for future developers to get started in our project? Any hints would be welcome.

**Comment by tobiasblass** [comment]
@elfenpiff  Thanks for the clarifications, I'll fix up the PR then.

> > It seems like the PR checklist assumes that a contributor can open a branch in the iceoryx repository,
> 
> This is not the case, why do you have this impression? At the moment the workflow is just to create a branch on the https://github.com/apexai/iceoryx fork (for Apex.AI employees) otherwise on your private fork.

Good question. I think the fact that there's a branch naming scheme suggested that to me (because why would you need a branch naming scheme on private forks?). Maybe it would be good to clarify this in the PR checklist.

> @tobiasblass From your point of view, do you have any suggestions for us how to make it easier for future developers to get started in our project? Any hints would be welcome.

I fully understand the need for traceability  (and thank you for the step-by-step instructions!). However, when the change is about minor fixes in the documentation, traceability is not as much of a concern (or at least it seems like this to me, I'm not an expert).  
At the same time, the effort to learn about the commit workflow can be higher than the actual work. Sure, that is not a big deal if you plan to commit regularly, but it discourages this kind of minor one-off fixes. 

You could consider having a streamlined process for "minor documentation fixes". It is probably a good idea to still insist on the ECA there, but it might be possible to skip the issue-creation/branch-linking step.

**Comment by elfenpiff** [comment]
@tobiasblass 

> Thanks for the clarifications, I'll fix up the PR then

I would like to merge your pull request in the next days, do you have time to fix up the PR?

**Comment by tobiasblass** [comment]
Closing in favor of #1363

**Pull request closed without merging**
