### PR TITLE
iox-#2121 Fix history request is out of limit.

### LINKED ISSUE #2121: historyRequest may larger than queueCapacity during creating Subscribers in PoshRuntimeImpl.
https://github.com/eclipse-iceoryx/iceoryx/blame/f0622f1f21c740a8e4510bd6d682db04cba566e7/iceoryx_posh/source/runtime/posh_runtime_impl.cpp#L237

At `if (subscriberOptions.historyRequest > subscriberOptions.queueCapacity)`, since `queueCapacity` may exceed the `MAX_QUEUE_CAPACITY`, `subscriberOptions.historyRequest` may need to compare with `options.queueCapacity`.

### PR DESCRIPTION
**Pull request by waliceSnow**
…ting the Roudi daemon to create a subscriber.

## Pre-Review Checklist for the PR Author

1. [x] Add a second reviewer for complex new features or larger refactorings
1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- fixes #2121

### CODE REVIEW

**Review by elBoberido — APPROVED** [review]
The PR looks good. LGTM :)

~~I might take a few hour until the ECA is synced and the respective CI check passes.~~ Oh, it is already green :)

**Comment by waliceSnow** [comment]
@elBoberido Hi. The "job Build & Test / run-integration-test (pull_request)" failed on the dpkg. Need I retry it?  Not sure how to fix it.

**Comment by elBoberido** [comment]
> @elBoberido Hi. The "job Build & Test / run-integration-test (pull_request)" failed on the dpkg. Need I retry it? Not sure how to fix it.

It seems it's just a hiccup. I triggered the CI again and the install step finished.

**Comment by elBoberido** [comment]
Looks good. Thanks for your contribution. The tasks for Cirrus CI are currently not running and the PR can be merged

**Comment by waliceSnow** [comment]
@elBoberido Thank you!

**Comment by elBoberido** [comment]
@waliceSnow you're welcome. Hope to see more PRs from you :)

**Pull request merged**
