### PR TITLE
iox-#1908 resolve the issue when the iox-roudi working with gateways

### LINKED ISSUE #1908: iox+dds together working issue
## Required information

**Operating system:**
Ubuntu 20.04 LTS

**Compiler version:**
GCC 9.4.0

**Eclipse iceoryx version:**
branch v2.0.3

**Observed result or behaviour:**
when iox and dds working together on two machines in the same net, if a particanpant restart, the communication can not recover again(unless restarting other participant)

**Expected result or behaviour:**
the participant exit and restart soon ,the communication should be recover soon.

**Conditions where it occurred / Performed steps:**
1,machine A: iox-roudi, iox-dds-gateway, /iceoryx_examples/icedelivery/iox-cpp-publisher(gateway start before publisher)
2,machine B: iox-roudi, iox-dds-gateway, /iceoryx_examples/icedelivery/iox-cpp-subscriber
3,exit the publisher(on A), and restart soon, the communication can not recover（unless restart the gateway on machine A)
4,exit the gateway on machine B, and restart soon, the communication can not recover(unless restart the subscriber)
5, some times the issue may not appears, this is because the variable m_isRunning.store(true) the function runMultithreaded(), which is in gateway_generic.inl,  may not work when the child thread discoverLoop and forwardLoop creating.
6,a deeper analysising find that the subsriber is not in the subscriber list when the publisher restart.(after adding debug info)
7,more info, the "break" in the for cycle in the sendToAllMatchingSubscriberPorts() in port_manager.cpp，generate the issue.
8,when I change the "break" to "continue", the issue is no longer exist .
9,but another issue is appear: when I add a publisher on machine B, the subscirber will receive the topic from publisher on the machine B twice.
10,when I exit the gateway on machine B, it can receive only one.
11,so, I guess, the twice topic may, one is go by iceoryx, the other one is go by dds(local).

### PR DESCRIPTION
**Pull request by woshiyunsk**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes #1908

### CODE REVIEW

**Comment by elfenpiff** [comment]
@woshiyunsk Did you sign the ECA with the same E-Mail address you used to commit the change (skyun2012@126.com)?

**Comment by woshiyunsk** [comment]
> @woshiyunsk Did you sign the ECA with the same E-Mail address you used to commit the change ([skyun2012@126.com](mailto:skyun2012@126.com))?
> 
> And thanks for the contribution, as soon as the ECA check is green we can merge it.

**Comment by woshiyunsk** [comment]
> > @woshiyunsk Did you sign the ECA with the same E-Mail address you used to commit the change ([skyun2012@126.com](mailto:skyun2012@126.com))?
> > And thanks for the contribution, as soon as the ECA check is green we can merge it.

OK, I had signed it already now. I'm not proficient in Engilish,  missed the information, sorry.

**Review by elBoberido — APPROVED** [review]
Looks good. Thanks for your contribution :)

**Review by elfenpiff — APPROVED** [review]

**Pull request merged**
