### PR TITLE
iox-#2007 Adapt docs with new meetup cadence

### LINKED ISSUE #2007: Change developer meetup to monthly cadence
## Brief feature description

Lately, there have been few topics discussed in the iceoryx developers' meetups. Hence, to combine the topics, the maintainers decided to change from a bi-weekly to a monthly cadence.

The documentation needs to be adapted.

### PR DESCRIPTION
**Pull request by mossmaurice**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] ~~Tests follow the [best practice for testing][testing]~~
1. [x] ~~Changelog updated [in the unreleased section][changelog] including API breaking changes~~
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] ~~All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`~~
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Notes for Reviewer

* Update documentation about monthly meetup cadence

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

- Closes #2007

### CODE REVIEW

**Comment by mossmaurice** [comment]
@ariexi Could you please change the Eclipse Zoom invite accordingly?  :pray: I would suggest the starting date for the new invite to be 2023/09/07.

**Review by elfenpiff — APPROVED** [review]

**Comment by ariexi** [comment]
> @ariexi Could you please change the Eclipse Zoom invite accordingly?  :pray: I would suggest the starting date for the new invite to be 2023/09/07.

Just one problem, I am currently on vacation and I will back on September 12th...
After that, I can change the invite, till then, you can use the current zoom link I guess.

**Comment by elBoberido** [comment]
@ariexi once you are back from vacation, would it be possible to use a free service which is build on open source and respects privacy for the meetings? Something like `jitsi`? It works without user name and password and everybody can easily join, e.g. https://meet.jit.si/eclipse-iceoryx. I'm always hesitant to enable the camera on Zoom.

cc @mossmaurice

**Comment by mossmaurice** [comment]
> would it be possible to use a free service which is build on open source and respects privacy for the meetings? Something like `jitsi`?

We can discuss that in the first developer meetup after the holiday season on 2023/09/07.

**Comment by ariexi** [comment]
> > would it be possible to use a free service which is build on open source and respects privacy for the meetings? Something like `jitsi`?
> 
> We can discuss that in the first developer meetup after the holiday season on 2023/09/07.

@mossmaurice, @elBoberido 
I am not able to provide another service then Zoom as Eclipse uses Zoom, sorry.
Is there a decision for changing the tool or will you still use Zoom?
Should I re-schedule the meeting series, beginning on September 7th?

**Comment by ariexi** [comment]
> > > would it be possible to use a free service which is build on open source and respects privacy for the meetings? Something like `jitsi`?
> > 
> > 
> > We can discuss that in the first developer meetup after the holiday season on 2023/09/07.
> 
> @mossmaurice, @elBoberido I am not able to provide another service then Zoom as Eclipse uses Zoom, sorry. Is there a decision for changing the tool or will you still use Zoom? Should I re-schedule the meeting series, beginning on September 7th?

I created a help desk issue at Eclipse

**Comment by elBoberido** [comment]
@ariexi regarding Zoom meeting. There was no conclusion at the last meeting, just that we would like to move to something else if it is allowed by the Eclipse guidelines or if we could ask Eclipse for an exception.

A good alternative would be the video call feature of gitter (nowadays just a rebranded  Element Web client). One can access the meeting with a link without the requirement to register. This is the link to a dummy meeting I created on gitter https://app.element.io/jitsi.html#conferenceDomain=meet.element.io&conferenceId=JitsiVtfrqukadefbqiqfxryxabai&isAudioOnly=false&startWithAudioMuted=false&startWithVideoMuted=true&isVideoChannel=false&displayName=&avatarUrl=&userId=&roomId=!AooDAAwkyNWwkMElpt%3Agitter.im&theme=&roomName=eclipse%2Ficeoryx&supportsScreensharing=false&language=de

**Comment by ariexi** [comment]
I had a chat w/ EF...
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3678

> Projects don't need to use Zoom. They can use whatever, as long as it's a open field for all.
> We regard a video conferencing solution as an [external resource](https://www.eclipse.org/projects/handbook/#resources-external).

So you have to follow the [external resource](https://www.eclipse.org/projects/handbook/#resources-external)

**Comment by elBoberido** [comment]
@ariexi thanks very much for clarifying this.

@mossmaurice can we put this on the agenda for the next meetup?

**Pull request merged**
