### PR TITLE
iox-#1668 Set chunk header originId always

### LINKED ISSUE #1668: originId for ChunkHeader sometimes missing
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 7.4.0

**Observed result or behaviour:**
The `m_originId` field of the `ChunkHeader` type is sometimes not set. This happens when the last unmanaged chunk can be reused in the `ChunkSender::tryAllocate` method.

**Expected result or behaviour:**
The `m_originId` field should always be set correctly.

**Conditions where it occurred / Performed steps:**
Call the chunk header `originId` setter and print it.

### PR DESCRIPTION
**Pull request by JakubSosnovec**
## Pre-Review Checklist for the PR Author

1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Closes #1668

### CODE REVIEW

**Comment by elBoberido** [comment]
@JakubSosnovec good catch. Can you write a tests which reproduces this bug? The corresponding file would be `test_popo_chunk_sender.cpp`.

Could you also change the last line in the description to `Closes #1688`, without making it a markdown link. Github will take care of it and also link the issue in the sidebar.

**Comment by JakubSosnovec** [comment]
@elBoberido I have added a test that fails on master branch, while it succeeds on this feature branch. I rather used the PublisherSubscriber integration tests, since I stumbled on this bug by actually using the public interface. If you also want a more fine-grained unit test, please let me know, I can also try to come up with it.

Additionally, I added a line to release notes and modified the PR description as you asked.

**Review by elfenpiff — APPROVED** [review]

**Comment by elfenpiff** [comment]
@JakubSosnovec this is great! Thank you.

**Review by elBoberido — APPROVED** [review]

**Comment by elBoberido** [comment]
@JakubSosnovec I've taken the liberty to check the remaining task :)

If you want you can add your copyright to the file. If you are fine without adding it, this can be merged.

**Review by elfenpiff — APPROVED** [review]

**Comment by elBoberido** [comment]
@JakubSosnovec just waiting for the CI to finish and then we can merge

**Comment by elBoberido** [comment]
@JakubSosnovec I think you need to resolve the the merge conflicts in the release notes. Unfortunately git cannot do it automatically.

**Comment by JakubSosnovec** [comment]
@elBoberido  I have rebased to latest master, there should be no merge conflict anymore.

**Comment by elBoberido** [comment]
@JakubSosnovec should be fine now. The FreeBSD build is a bit flaky but usually it doesn't fail twice and I should be able to merge in half an hour or so.

Btw, on Thursday we have our bi-weekly developer meetup. Would be great to meet you there and maybe get some input on stuff you are missing or where you use iceoryx. If you are allowed to talk about it of course :)

**Review by elBoberido — APPROVED** [review]

**Review by elfenpiff — APPROVED** [review]

**Comment by JakubSosnovec** [comment]
@elBoberido  thanks for the invite to the developer meetup :) I just checked with my manager regarding what I can talk about, and I have quite a lot of freedom. So, I will join the meetup later today, lets talk there :)

**Pull request merged**
