### PR TITLE
Iox #285 improve unit test coverage for sharedchunk-mempool-mepooconfig

### PR DESCRIPTION
**Pull request by nihalchari**
## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed
1. [ ] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Notes for Reviewer
code contributed by @georgemathewjerrin

## Checklist for the PR Reviewer

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code according to our coding style and naming conventions
- [ ] Unit tests have been written for new behavior
- [ ] Public API changes are documented via doxygen
- [ ] Copyright owner are updated in the changed files
- [ ] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [ ] All checkboxes in the PR checklist are checked or crossed out
1. [ ] Merge

## References

- Partly closes **#285**

### CODE REVIEW

**Comment by dkroenke** [comment]
@nihalchari @georgemathewjerrin Hi, i'm very sorry to say it, but this PR links to the wrong issue. #285 is for adding cmake tools and stresstests and not for extending unittests. It is better to not mix up things too much in the issues, because it is later  needed for traceability.
As is see you are adding tests to iceoryx_posh right? It make sense to create a separate issue for that where all test enhancements for posh are collected.

**Review by dkroenke — CHANGES_REQUESTED** [review]
Please create a new issue for testing in iceoryx_posh with a proper description and rework the commits so that they link to the created issue.

**Comment by nihalchari** [comment]
okay @dkroenke , i took this issue as it was mentioned "add more tests and tools"  earlier. Ill create new as suggested.

**Comment by nihalchari** [comment]
i created new issue, #496
@dkroenke  could you please add test label for it? 
@georgemathewjerrin please rework the commits so that they link to new issue #496

**Comment by dkroenke** [comment]
additional point: the branchname and pull-request title is wrong. Please link the PR then also to the issue.

**Comment by nihalchari** [comment]
I closing this PR, i will create new one

**Pull request closed without merging**
