### PR TITLE
iox-#2230 Make exported cmake packages relocateable

### LINKED ISSUE #2230: Exported packages are not relocateable
## Required information

**Operating system:**
E.g. Ubuntu 22.04 LTS

**Compiler version:**
GCC 11.4.0

**Eclipse iceoryx version:**
`master` branch

**Observed result or behaviour:**
We created a Yocto recipe to cross-compile iceoryx:
```
#iceoryx_git.bb
SECTION = "iceoryx - true zero-copy inter-process-communication"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=46d6aa0ba1fa2ed247cd8d42f20b72f4"

SRC_URI = "git://github.com/eclipse/iceoryx.git;protocol=https;branch=master"
SRCREV = "1e17b23d50e7ac2243f43969d90e7f5e8b60afca"

PV = "2.0.5+git"

SRC_URI += "file://iceoryx-roudi.service"

inherit cmake systemd

S = "${WORKDIR}/git"

EXTRA_OECMAKE = " \
	-H${S}/iceoryx_meta \
"

PACKAGECONFIG ?= "bindingc ccache toml shared introspection"

PACKAGECONFIG[all] = "-DBUILD_ALL=ON,-DBUILD_ALL=OFF,ncurses"
PACKAGECONFIG[test] = "-DBUILD_TEST=ON,-DBUILD_TEST=OFF"
PACKAGECONFIG[shared] = "-DBUILD_SHARED_LIBS=ON,-DBUILD_SHARED_LIBS=OFF"
PACKAGECONFIG[bindingc] = "-DBINDING_C=ON,-DBINDINGC=OFF"
PACKAGECONFIG[examples] = "-DEXAMPLES=ON,-DEXAMPLES=OFF"
PACKAGECONFIG[introspection] = "-DINTROSPECTION=ON,-DINTROSPECTION=OFF,ncurses"
PACKAGECONFIG[toml] = "-DTOML_CONFIG=ON -DDOWNLOAD_TOML_LIB=ON,-DTOML_CONFIG=OFF -DDOWNLOAD_TOML_LIB=OFF"
PACKAGECONFIG[ccache] = "-DCCACHE=ON,-DCCACHE=OFF"

SYSTEMD_AUTO_ENABLE = "enable"
SYSTEMD_SERVICE:${PN} = "iceoryx-roudi.service"

do_install:append() {
	install -d ${D}${systemd_system_unitdir}
	install -m 0644 ${WORKDIR}/iceoryx-roudi.service ${D}${systemd_system_unitdir}
}

DEPENDS += "acl pkgconfig"
FILES:${PN} += "/usr/etc/* ${systemd_system_unitdir}/*"
```
It works but when installing the exported packages in an SDK and trying to use find_package() (e. g. `find_package(iceoryx_posh CONFIG REQUIRED)`) within CMakeLists.txt, it fails:

```
[cmake] CMake Error at /opt/sdk/sysroots/armv8a_tegra-lms-linux/usr/lib/cmake/iceoryx_platform/iceoryx_platformTargets.cmake:79 (message):
[cmake]   The imported target "iceoryx_platform::iceoryx_platform" references the
[cmake]   file
[cmake] 
[cmake]      "/usr/lib/libiceoryx_platform.so.2.90.0"
[cmake] 
[cmake]   but this file does not exist.
```

The underlying problem is that the _IMPORT_PREFIX in the target import files is fixed and not relative to the installation path, e. g.:
```
#iceoryx_platformTargets.cmake
set(_IMPORT_PREFIX "/usr/local")
```

**Expected result or behaviour:**
Installed packages should be relocateable. The _IMPORT_PREFIX should be relative to the target import file.

**Conditions where it occurred / Performed steps:**
Install iceoryx packages in a directory that differs from the standard installation directory used by the environment the project was built on.

### PR DESCRIPTION
**Pull request by lms-ts**
## Pre-Review Checklist for the PR Author

1. [x] Add a second reviewer for complex new features or larger refactorings
1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [x] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Closes #2230

### CODE REVIEW

**Comment by elBoberido** [comment]
It seems the PR breaks the out of tree builds. Maybe cmake does not find it anymore. Is the actual install location changed?

**Comment by lms-ts** [comment]
@elBoberido I have tested again on Ubuntu, the installation directory is per default still /usr/local or whatever is specified with `-DCMAKE_INSTALL_PREFIX`

**Comment by elBoberido** [comment]
@lms-ts can you successfully run `tools/iceoryx_build_test.sh clean out-of-tree`

**Comment by lms-ts** [comment]
@elBoberido Thanks for the int. No, it fails with

```
CMake Error at CMakeLists.txt:26 (include):
  include could not find requested file:

    IceoryxPackageHelper


CMake Error at CMakeLists.txt:27 (include):
  include could not find requested file:

    IceoryxPlatform


CMake Error at CMakeLists.txt:28 (include):
  include could not find requested file:

    IceoryxPlatformSettings


CMake Error at CMakeLists.txt:30 (iox_add_executable):
  Unknown CMake command "iox_add_executable".

```

I will try to fix that tomorrow.

**Review by elBoberido — APPROVED** [review]

**Comment by elBoberido** [comment]
> @elBoberido iceoryxplatformConfig.cmake (which is in the same folder as iceoryx_platformTargets.cmake) is called when using `find_package(iceoryx_platform CONFIG REQUIRED)` and `CMAKE_CURRENT_LIST_DIR` is the current location of iceoryxplatformConfig.cmake where the modules reside which are included by `include()`. So if the installation is relocated, `CMAKE_CURRENT_LIST_DIR` will change accordingly.

Right. Totally forgot that it will only be executed in the out ot tree build.

Thanks for your contributions

**Pull request merged**
