### PR TITLE
iox-#2011 Patch cpptoml to use at least CMake 3.5.

### PR DESCRIPTION
**Pull request by clalancette**
Newer versions of CMake (like CMake 3.28 in Ubuntu 24.04) complain when projects ask for compatibility with versions of CMake earlier than 3.5.  Bump cpptoml to at least 3.5 here.

## Pre-Review Checklist for the PR Author

1. [N/A] Add a second reviewer for complex new features or larger refactorings
1. [x] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [N/A] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [N/A] Branch follows the naming format (`iox-123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [N/A] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [N/A] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed (except `task-list-completed`)
1. [N/A] All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#coding-style
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/release-notes/iceoryx-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] All touched (C/C++) source code files from `iceoryx_hoofs` have been added to `./clang-tidy-diff-scans.txt`
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

- Relates to #2011

### CODE REVIEW

**Comment by elBoberido** [comment]
I think you can use #2011 for this PR. Please add `iox-#2011` to your commit message.

Furthermore, can you please change `vmactions/freebsd-vm@v0` to `vmactions/freebsd-vm@v1` in `.github/workflows/build-test.yml`.

Additionally, to make the CI happy can you adjust the patch to work similarly to this https://github.com/eclipse-iceoryx/iceoryx/blob/release_2.0/cmake/googletest/CMakeLists.txt#L73-L82

**Comment by clalancette** [comment]
> I think you can use #2011 for this PR. Please add `iox-#2011` to your commit message.

Done now.



> Furthermore, can you please change `vmactions/freebsd-vm@v0` to `vmactions/freebsd-vm@v1` in `.github/workflows/build-test.yml`.

Also done.

> Additionally, to make the CI happy can you adjust the patch to work similarly to this https://github.com/eclipse-iceoryx/iceoryx/blob/release_2.0/cmake/googletest/CMakeLists.txt#L73-L82

I don't think that is the correct logic for this patch.  In particular, we want to apply this on Windows as well, as with a newer version of CMake there, we will have the same warning.

**Comment by elBoberido** [comment]
@clalancette the same logic can be used to apply the patch on Windows. I'm not sure anymore why we skipped Windows with gTest.

The current proposal has the drawback that one cannot call `cmake -B build -Hiceoryx_meta` multiple times, e.g. when changing some compile time options, without cleaning the whole build directory. The logic we use for gTest only generates a warning instead of an error on subsequent calls. 

Can you adapt this PR similarly to #2247? I set the version to v3.16 since that's what we require anyway.

I guess you would also like to see a v2.0.6 release after this is merged, right?

**Comment by clalancette** [comment]
Sorry for the delay here, just picking this back up.

Thanks for doing that work on `master`, that made my life really easy.  This now just becomes a backport of that.  With that in mind, please see 94224d0.

> I guess you would also like to see a v2.0.6 release after this is merged, right?

Yes, that would be fantastic, thank you.

**Review by elBoberido — APPROVED** [review]

**Comment by elBoberido** [comment]
@clalancette is there a deadline by when you need the v2.0.6 release?

I also just noticed that the last commit does not start with the issue number. Can you please amend the commit message and force push?

**Comment by clalancette** [comment]
> I also just noticed that the last commit does not start with the issue number. Can you please amend the commit message and force push?

Fixed now.

> @clalancette is there a deadline by when you need the v2.0.6 release?

Earlier is better, but the drop-dead date is in about 4 weeks.

**Comment by elBoberido** [comment]
It seems there are issues with the FreeBSD action and the codecov upload. I'll merge and take care of these issues in a follow up PR since they are not related to your changes

**Comment by clalancette** [comment]
> It seems there are issues with the FreeBSD action and the codecov upload. I'll merge and take care of these issues in a follow up PR since they are not related to your changes

Thank you, it is much appreciated!

**Comment by elBoberido** [comment]
@clalancette I was just pinged by another iceoryx committer that they got some emails from the ROS buildfarm after the merge. They are not quite sure if something broke but I also do not have access to those mails. Can you confirm that this merge did not break anything?

**Comment by Crola1702** [comment]
Hey! I think this PR triggered a warning in ROS2 CI: 

Reference build: 
* https://build.ros2.org/view/Hci/job/Hci__nightly-release_ubuntu_jammy_amd64/236/
* https://build.ros2.org/view/Ici/job/Ici__nightly-release_ubuntu_jammy_amd64/115/
* https://build.ros2.org/view/Rci/job/Rci__nightly-fastrtps_ubuntu_jammy_amd64/796/

In iceoryx_posh output:

```
[100%] Built target ext_cpptoml
error: patch failed: CMakeLists.txt:1
error: CMakeLists.txt: patch does not apply
CMake Warning at cmake/cpptoml/CMakeLists.txt:81 (message):
CMake step [patch] for 'cpptoml-build' failed! Error code: 1! Build of 
'cpptoml-build' might fail
```

CC: @clalancette

**Comment by elBoberido** [comment]
@Crola1702 this should only happen it the patch is already applied. I think I can fix this. Will create a PR to check if the patch can be reversed to check if it is already applied. If if fails, the patch will be applied.

cc @clalancette

**Pull request merged**
