### PR TITLE
Iox #484 improve posix mutex test

### LINKED ISSUE #484: Improve POSIX mutex test
## Brief feature description

Using the While loop will consume CPU cycles and other threads will have to wait. Using the sleep_for will free up the CPU for the define time so that other threads can utilize.-

## Detailed information

The test_posix_mutex.cpp has DestructorFailsOnLockedMutex test case. It uses deadline timer with a While loop and this can be improved by replacing with sleep_for. Hint suggestion from @elBoberido ,
`EXPECT_DEATH({{
    iox::posix::mutex mtx{false};
    mtx.lock;
}}, ".*");`

### PR DESCRIPTION
**Pull request by nihalchari**
## Pre-Review Checklist for the PR Author

1. [x] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`iox-#123 commit text`)
    - [x] Commit messages are signed (`git commit -s`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Update the PR title
   - Follow the same conventions as for commit messages
   - Link to the relevant issue
1. [x] Relevant issues are linked
1. [x] Add sensible notes for the reviewer
1. [x] All checks have passed
1. [x] Assign PR to reviewer

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php

## Notes for Reviewer
code contributed by @shankar-in

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code according to our coding style and naming conventions
- [x] Unit tests have been written for new behavior
- [x] Public API changes are documented via doxygen
- [x] Copyright owner are updated in the changed files
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## Post-review Checklist for the Eclipse Committer

1. [ ] All checkboxes in the PR checklist are checked or crossed out
1. [ ] Merge

## References

- Closes #484

### CODE REVIEW

**Comment by nihalchari** [comment]
@dkroenke wrt https://docs.github.com/en/github/managing-your-work-on-github/managing-labels#applying-labels-to-issues-and-pull-requests, under "Applying labels to issues and pull requests point no. 3" , for me mentioned checkbox is not visible

**Comment by elBoberido** [comment]
@shankar-in did you try my suggestion?
```
EXPECT_DEATH({{ iox::posix::mutex mtx{false}; mtx.lock; }}, ".*");
```
From the test name, it should just check the destruction of a locked mutex. There is no need to use threads for this.

**Comment by shankar-in** [comment]
@elBoberido No I didnt try that. Doing that now. Will update that.

**Comment by elBoberido** [comment]
> @elBoberido No I didnt try that. Doing that now. I have a clarification. The statement `iox::posix::mutex mtx{false}; mtx.lock; ` cause the process to die? Does the double inner block `{{ }}` make this significant?. Is my understanding correct? Could you pls explain?

At the end of the scope the dtor is called, which causes the process to die if the mutex is still locked. It might be sufficient to have it just in one pair of `{}`.

**Review by elBoberido — APPROVED** [review]

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

**Comment by marthtz** [comment]
I like it! Unnecessary code removed and much more readable and on point! However, a comment would probably be nice ;)

**Review by marthtz — APPROVED** [review]

**Pull request merged**
